name: Checks

on:  
  push:
  pull_request:
    branches:
      - main

jobs:  
  cheks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: npm ci
    - run: npm run lint
    - run: npm run format
    - run: npm run test test --if-present
    - run: npm run test test:e2e --if-present
    - run: npm run build
